---
title: "Séance 4 - TP"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

# Travail pratique pour la séance 4

## L'enquête emploi

L'enquête Emploi en continu est la seule source fournissant une mesure des concepts d'activité, chômage, emploi et inactivité tels qu'ils sont définis par le Bureau international du travail (BIT). Elle comporte par ailleurs des informations très nombreuses sur les caractéristiques des personnes (sexe, âge, diplôme, expérience, etc.), les conditions d'emploi (profession, type de contrat, temps de travail, ancienneté dans l'emploi, sous-emploi, etc.), les situations de non-emploi (méthodes de recherche d'emploi, études, retraite, etc.).

Le code suivant charge une extraction de l'enquête emploi de 2012 sur laquelle vous allez travailler.\
Le dictionnaire des codes est disponible à l'adresse suivante : <https://data.progedo.fr/studies/doi/10.13144/lil-1000b?tab=variables>

```{r}
library(tidyverse)
library(questionr)

# Chargement des données
eec <- aws.s3::s3read_using(FUN = data.table::fread,
                           object = "/diffusion/eec.csv",
                           bucket = "aubinpoissonnier",
                           opts = list("region" = ""))
```

Voici en plus un tableau récapitulatif du codage de certaines variables de la base.

| Nom de variable                                               | Codage                                                                                                |
|----------------------------|--------------------------------------------|
| TPP : Nature du temps de travail                              | 1 : Temps complet ; 2 : Temps partiel ; 3 : sans objet                                                |
| ACTEU : Statut d'activité (définition BIT)                    | 1 : Actif occupé ; 2 : Chômeur ; 3 : Inactif                                                          |
| STC : Statut d'emploi                                         | 1 : À son compote ; 2 : Chef d'entreprise salarié ; 3 : Salarié ; 4 : Aide familiale                  |
| AIDREF : Travail non rémunéré pendant la semaine de référence | 1 : Oui, aide familiale ; 2 : Oui, stage ; 3 : Oui, bénévolat ; 4 : Oui, travail domestique ; 5 : Non |

## Tester la dépendance entre le sexe et la nature du temps de travail

Construisez deux tableaux croisés.

-   Le premier représente la distribution des catégories socio-professionnelles (variable `CSE`) **regroupées au niveau 1** (elles sont détaillées au niveau 2 initialement dans la base) selon le sexe (variable `SEXE`).

-   Le second représente la distribution de la nature du temps de travail (variable `TPP`) en fonction du sexe.

Pour chaque tableau, vous rédigerez des paragraphes de lecture des tableaux obtenus en respectant les normes revues pendant la séance. Ensuite, vous mettrez en place deux tests d'hypothèses pour conclure sur la significativité statistique des interdépendances entre les variables.

## Créer un graphique synthétique

Votre objectif consiste à créer un graphique qui synthétise trois choses :

-   La répartition de la classe socio-professionelle (dimension 1, variable `CSE`)

-   représentée en fonction du sexe (dimension 2, variable `SEXE`)

-   qui montre pour chaque catégorie socio-professionnelle la part de personnes en temps partiel, en temps plein et la part de personne non concernées par cette distinction (dimension 3, variable `TPP`)

La lecture de ce graphique doit permettre de répondre à ces questions : quels sont les secteurs d'emploi des hommes et des femmes et dans quels secteurs les temps partiels sont-ils les plus communs chez les hommes et chez les femmes ?

Il faudra ensuite annoter le graphique et le rendre le plus lisible possible. Finalement, vous devrez rédiger une lecture du graphique.

## 
